import { NavBar } from "@/components";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/features/sidebar";
import "@/styles/app.css";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Inventory API Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <NavBar />
            <div className="grid gap-4 p-4">{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
