import { Body, NavBar } from "@/components";
import { AppToaster } from "@/components/AppToaster";
import { SidebarProvider } from "@/components/ui";
import { AppSidebar } from "@/features/sidebar";
import { ReactQueryProvider } from "@/providers";
import type { Metadata } from "next";
import "./styles/app.css";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Inventory API Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Body>
        <AppToaster />
        <ReactQueryProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className="mr-4 ml-2 w-full">
              <NavBar />
              <div className="mt-4 grid gap-4">{children}</div>
            </main>
          </SidebarProvider>
        </ReactQueryProvider>
      </Body>
    </html>
  );
}
