import { Product } from "@/features/product";

const competitorProducts: Product[] = [
  // ===================== RAZER =====================
  // Gaming Mouse
  {
    id: 101,
    supplier_id: 10,
    name: "Razer DeathAdder V2",
    supplier: "Razer",
    description: "Ergonomic wired gaming mouse with optical sensor.",
    category: "Gaming Mouse",
    cost: 69.99,
  },
  {
    id: 102,
    supplier_id: 10,
    name: "Razer Basilisk V3",
    supplier: "Razer",
    description: "Wired gaming mouse with customizable scroll wheel.",
    category: "Gaming Mouse",
    cost: 79.99,
  },
  // Gaming Keyboard
  {
    id: 103,
    supplier_id: 10,
    name: "Razer BlackWidow V3",
    supplier: "Razer",
    description: "Mechanical gaming keyboard with RGB lighting.",
    category: "Gaming Keyboard",
    cost: 139.99,
  },
  {
    id: 104,
    supplier_id: 10,
    name: "Razer Huntsman Mini",
    supplier: "Razer",
    description: "60% compact gaming keyboard with optical switches.",
    category: "Gaming Keyboard",
    cost: 119.99,
  },
  // Gaming Headset Wired
  {
    id: 105,
    supplier_id: 10,
    name: "Razer Kraken X",
    supplier: "Razer",
    description: "Lightweight wired headset with 7.1 surround.",
    category: "Gaming Headset (Wired)",
    cost: 49.99,
  },
  {
    id: 106,
    supplier_id: 10,
    name: "Razer Nari Essential",
    supplier: "Razer",
    description: "Wired gaming headset with THX spatial audio.",
    category: "Gaming Headset (Wired)",
    cost: 79.99,
  },
  // Regular Mouse
  {
    id: 107,
    supplier_id: 10,
    name: "Razer Atheris",
    supplier: "Razer",
    description: "Compact wireless mouse for work and travel.",
    category: "Mouse",
    cost: 49.99,
  },
  {
    id: 108,
    supplier_id: 10,
    name: "Razer Pro Click Mini",
    supplier: "Razer",
    description: "Wireless productivity mouse with ergonomic design.",
    category: "Mouse",
    cost: 69.99,
  },
  // Webcam
  {
    id: 109,
    supplier_id: 10,
    name: "Razer Kiyo",
    supplier: "Razer",
    description: "1080p streaming webcam with adjustable ring light.",
    category: "Webcam",
    cost: 99.99,
  },
  // Microphone
  {
    id: 110,
    supplier_id: 10,
    name: "Razer Seiren X",
    supplier: "Razer",
    description: "Compact USB microphone for streaming.",
    category: "Microphone",
    cost: 99.99,
  },

  // ===================== CORSAIR =====================
  {
    id: 111,
    supplier_id: 11,
    name: "Corsair M65 RGB Elite",
    supplier: "Corsair",
    description: "FPS gaming mouse with customizable weights.",
    category: "Gaming Mouse",
    cost: 69.99,
  },
  {
    id: 112,
    supplier_id: 11,
    name: "Corsair Scimitar RGB",
    supplier: "Corsair",
    description: "MMO gaming mouse with 12 side buttons.",
    category: "Gaming Mouse",
    cost: 79.99,
  },
  {
    id: 113,
    supplier_id: 11,
    name: "Corsair K70 RGB MK.2",
    supplier: "Corsair",
    description: "Mechanical gaming keyboard with Cherry MX switches.",
    category: "Gaming Keyboard",
    cost: 159.99,
  },
  {
    id: 114,
    supplier_id: 11,
    name: "Corsair K55 RGB",
    supplier: "Corsair",
    description: "Membrane keyboard with programmable macros.",
    category: "Gaming Keyboard",
    cost: 49.99,
  },
  {
    id: 115,
    supplier_id: 11,
    name: "Corsair HS50 Pro",
    supplier: "Corsair",
    description: "Wired stereo gaming headset.",
    category: "Gaming Headset (Wired)",
    cost: 49.99,
  },
  {
    id: 116,
    supplier_id: 11,
    name: "Corsair VOID RGB Elite",
    supplier: "Corsair",
    description: "Wired 7.1 surround gaming headset.",
    category: "Gaming Headset (Wired)",
    cost: 79.99,
  },
  {
    id: 117,
    supplier_id: 11,
    name: "Corsair Harpoon RGB",
    supplier: "Corsair",
    description: "Affordable wireless mouse for productivity.",
    category: "Mouse",
    cost: 49.99,
  },
  {
    id: 118,
    supplier_id: 11,
    name: "Corsair K83 Wireless",
    supplier: "Corsair",
    description: "Compact wireless keyboard with touchpad.",
    category: "Keyboard",
    cost: 99.99,
  },
  {
    id: 119,
    supplier_id: 11,
    name: "Corsair FaceCam",
    supplier: "Corsair",
    description: "1080p streaming webcam with high-quality optics.",
    category: "Webcam",
    cost: 149.99,
  },
  {
    id: 120,
    supplier_id: 11,
    name: "Corsair ST100 RGB Microphone",
    supplier: "Corsair",
    description: "USB microphone with RGB stand.",
    category: "Microphone",
    cost: 129.99,
  },

  // ===================== STEELSERIES =====================
  {
    id: 121,
    supplier_id: 48,
    name: "SteelSeries Rival 3",
    supplier: "SteelSeries",
    description: "Wired optical gaming mouse with true 1-to-1 tracking.",
    category: "Gaming Mouse",
    cost: 39.99,
  },
  {
    id: 122,
    supplier_id: 48,
    name: "SteelSeries Sensei Ten",
    supplier: "SteelSeries",
    description: "Ambidextrous wired gaming mouse.",
    category: "Gaming Mouse",
    cost: 69.99,
  },
  {
    id: 123,
    supplier_id: 48,
    name: "SteelSeries Apex 7",
    supplier: "SteelSeries",
    description: "Mechanical gaming keyboard with OLED display.",
    category: "Gaming Keyboard",
    cost: 159.99,
  },
  {
    id: 124,
    supplier_id: 48,
    name: "SteelSeries Apex 3",
    supplier: "SteelSeries",
    description: "RGB membrane gaming keyboard.",
    category: "Gaming Keyboard",
    cost: 49.99,
  },
  {
    id: 125,
    supplier_id: 48,
    name: "SteelSeries Arctis 5",
    supplier: "SteelSeries",
    description: "Wired 7.1 surround headset with RGB lighting.",
    category: "Gaming Headset (Wired)",
    cost: 99.99,
  },
  {
    id: 126,
    supplier_id: 48,
    name: "SteelSeries Arctis 1 Wired",
    supplier: "SteelSeries",
    description: "Affordable wired gaming headset.",
    category: "Gaming Headset (Wired)",
    cost: 49.99,
  },
  {
    id: 127,
    supplier_id: 48,
    name: "SteelSeries Rival 600",
    supplier: "SteelSeries",
    description: "Dual-sensor wired mouse.",
    category: "Mouse",
    cost: 79.99,
  },
  {
    id: 128,
    supplier_id: 48,
    name: "SteelSeries Apex Pro TKL",
    supplier: "SteelSeries",
    description: "Tenkeyless mechanical keyboard with OmniPoint switches.",
    category: "Keyboard",
    cost: 199.99,
  },
  {
    id: 129,
    supplier_id: 48,
    name: "SteelSeries StreamCam",
    supplier: "SteelSeries",
    description: "1080p webcam optimized for content creators.",
    category: "Webcam",
    cost: 149.99,
  },
  {
    id: 130,
    supplier_id: 48,
    name: "SteelSeries Sonar USB Microphone",
    supplier: "SteelSeries",
    description: "USB microphone with studio-quality sound.",
    category: "Microphone",
    cost: 129.99,
  },

  // ===================== HYPERX =====================
  {
    id: 131,
    supplier_id: 27,
    name: "HyperX Pulsefire FPS Pro",
    supplier: "HyperX",
    description: "Wired gaming mouse with Pixart sensor.",
    category: "Gaming Mouse",
    cost: 59.99,
  },
  {
    id: 132,
    supplier_id: 27,
    name: "HyperX Pulsefire Dart",
    supplier: "HyperX",
    description: "Wireless gaming mouse with long battery life.",
    category: "Gaming Mouse",
    cost: 79.99,
  },
  {
    id: 133,
    supplier_id: 27,
    name: "HyperX Alloy FPS Pro",
    supplier: "HyperX",
    description: "Tenkeyless mechanical gaming keyboard with red switches.",
    category: "Gaming Keyboard",
    cost: 109.99,
  },
  {
    id: 134,
    supplier_id: 27,
    name: "HyperX Alloy Elite 2",
    supplier: "HyperX",
    description: "Full-size mechanical RGB gaming keyboard.",
    category: "Gaming Keyboard",
    cost: 159.99,
  },
  {
    id: 135,
    supplier_id: 27,
    name: "HyperX Cloud Stinger",
    supplier: "HyperX",
    description: "Lightweight wired headset with 7.1 virtual surround.",
    category: "Gaming Headset (Wired)",
    cost: 49.99,
  },
  {
    id: 136,
    supplier_id: 27,
    name: "HyperX Cloud Alpha",
    supplier: "HyperX",
    description: "Wired stereo gaming headset with dual chamber drivers.",
    category: "Gaming Headset (Wired)",
    cost: 99.99,
  },
  {
    id: 137,
    supplier_id: 27,
    name: "HyperX Pulsefire Raid",
    supplier: "HyperX",
    description: "Wired mouse optimized for MMO gaming.",
    category: "Mouse",
    cost: 59.99,
  },
  {
    id: 138,
    supplier_id: 27,
    name: "HyperX Alloy Core RGB",
    supplier: "HyperX",
    description: "Membrane keyboard with RGB lighting.",
    category: "Keyboard",
    cost: 49.99,
  },
  {
    id: 139,
    supplier_id: 27,
    name: "HyperX SoloCast",
    supplier: "HyperX",
    description: "USB condenser microphone for streaming.",
    category: "Microphone",
    cost: 69.99,
  },
  {
    id: 140,
    supplier_id: 27,
    name: "HyperX QuadCast S",
    supplier: "HyperX",
    description: "Premium USB microphone with RGB lighting.",
    category: "Microphone",
    cost: 139.99,
  },
];

export const products: Product[] = [
  // 🎮 Gaming Mice
  {
    id: 1,
    supplier_id: 1,
    name: "Logitech G502 HERO",
    supplier: "Logitech",
    description: "High-performance wired gaming mouse with 25K sensor.",
    category: "Gaming Mouse",
    cost: 79.99,
  },
  {
    id: 2,
    supplier_id: 1,
    name: "Logitech G Pro X Superlight",
    supplier: "Logitech",
    description: "Lightweight wireless gaming mouse designed for esports.",
    category: "Gaming Mouse",
    cost: 149.99,
  },
  {
    id: 3,
    supplier_id: 1,
    name: "Logitech G203 Lightsync",
    supplier: "Logitech",
    description: "Budget-friendly RGB gaming mouse with 8K DPI.",
    category: "Gaming Mouse",
    cost: 39.99,
  },
  {
    id: 4,
    supplier_id: 1,
    name: "Logitech G305 Lightspeed",
    supplier: "Logitech",
    description:
      "Wireless gaming mouse with HERO sensor and 250h battery life.",
    category: "Gaming Mouse",
    cost: 59.99,
  },
  {
    id: 5,
    supplier_id: 1,
    name: "Logitech G402 Hyperion Fury",
    supplier: "Logitech",
    description: "FPS-optimized wired gaming mouse with hybrid sensor.",
    category: "Gaming Mouse",
    cost: 49.99,
  },

  // 🎮 Gaming Keyboards
  {
    id: 6,
    supplier_id: 1,
    name: "Logitech G915 TKL",
    supplier: "Logitech",
    description:
      "Wireless RGB mechanical gaming keyboard with low profile switches.",
    category: "Gaming Keyboard",
    cost: 229.99,
  },
  {
    id: 7,
    supplier_id: 1,
    name: "Logitech G Pro X",
    supplier: "Logitech",
    description:
      "Esports-grade mechanical keyboard with hot-swappable switches.",
    category: "Gaming Keyboard",
    cost: 149.99,
  },
  {
    id: 8,
    supplier_id: 1,
    name: "Logitech G413",
    supplier: "Logitech",
    description: "Backlit mechanical gaming keyboard with Romer-G switches.",
    category: "Gaming Keyboard",
    cost: 89.99,
  },
  {
    id: 9,
    supplier_id: 1,
    name: "Logitech G213 Prodigy",
    supplier: "Logitech",
    description: "Spill-resistant gaming keyboard with RGB lighting.",
    category: "Gaming Keyboard",
    cost: 69.99,
  },
  {
    id: 10,
    supplier_id: 1,
    name: "Logitech G910 Orion Spectrum",
    supplier: "Logitech",
    description: "Full-size RGB mechanical keyboard with ARX control dock.",
    category: "Gaming Keyboard",
    cost: 179.99,
  },

  // 🎧 Gaming Headset (Wired)
  {
    id: 11,
    supplier_id: 1,
    name: "Logitech G432",
    supplier: "Logitech",
    description: "Wired gaming headset with 7.1 surround sound.",
    category: "Gaming Headset (Wired)",
    cost: 79.99,
  },
  {
    id: 12,
    supplier_id: 1,
    name: "Logitech G Pro X",
    supplier: "Logitech",
    description: "Wired esports headset with Blue VO!CE microphone tech.",
    category: "Gaming Headset (Wired)",
    cost: 129.99,
  },
  {
    id: 13,
    supplier_id: 1,
    name: "Logitech G633 Artemis Spectrum",
    supplier: "Logitech",
    description: "RGB wired gaming headset with DTS surround sound.",
    category: "Gaming Headset (Wired)",
    cost: 99.99,
  },
  {
    id: 14,
    supplier_id: 1,
    name: "Logitech G230",
    supplier: "Logitech",
    description: "Lightweight wired stereo gaming headset.",
    category: "Gaming Headset (Wired)",
    cost: 49.99,
  },
  {
    id: 15,
    supplier_id: 1,
    name: "Logitech G35",
    supplier: "Logitech",
    description: "Wired surround sound gaming headset with on-ear controls.",
    category: "Gaming Headset (Wired)",
    cost: 89.99,
  },

  // 🎧 Gaming Headset (Wireless)
  {
    id: 16,
    supplier_id: 1,
    name: "Logitech G733 Lightspeed",
    supplier: "Logitech",
    description:
      "Wireless gaming headset with RGB lighting and Blue VO!CE mic.",
    category: "Gaming Headset (Wireless)",
    cost: 149.99,
  },
  {
    id: 17,
    supplier_id: 1,
    name: "Logitech G935",
    supplier: "Logitech",
    description: "Wireless 7.1 surround gaming headset with 12-hour battery.",
    category: "Gaming Headset (Wireless)",
    cost: 169.99,
  },
  {
    id: 18,
    supplier_id: 1,
    name: "Logitech G533",
    supplier: "Logitech",
    description: "DTS Headphone:X surround wireless gaming headset.",
    category: "Gaming Headset (Wireless)",
    cost: 129.99,
  },
  {
    id: 19,
    supplier_id: 1,
    name: "Logitech G930",
    supplier: "Logitech",
    description: "Wireless gaming headset with Dolby 7.1 surround sound.",
    category: "Gaming Headset (Wireless)",
    cost: 139.99,
  },
  {
    id: 20,
    supplier_id: 1,
    name: "Logitech Astro A50 (Logitech-owned brand)",
    supplier: "Logitech",
    description: "Premium wireless gaming headset with charging dock.",
    category: "Gaming Headset (Wireless)",
    cost: 299.99,
  },

  // 🖱️ Regular Mice
  {
    id: 21,
    supplier_id: 1,
    name: "Logitech MX Master 3S",
    supplier: "Logitech",
    description: "Advanced wireless mouse with MagSpeed scroll wheel.",
    category: "Mouse",
    cost: 99.99,
  },
  {
    id: 22,
    supplier_id: 1,
    name: "Logitech MX Anywhere 3",
    supplier: "Logitech",
    description: "Portable wireless mouse for mobile work.",
    category: "Mouse",
    cost: 79.99,
  },
  {
    id: 23,
    supplier_id: 1,
    name: "Logitech M510",
    supplier: "Logitech",
    description: "Wireless mouse with back/forward buttons.",
    category: "Mouse",
    cost: 39.99,
  },
  {
    id: 24,
    supplier_id: 1,
    name: "Logitech M185",
    supplier: "Logitech",
    description: "Simple, budget-friendly wireless mouse.",
    category: "Mouse",
    cost: 19.99,
  },
  {
    id: 25,
    supplier_id: 1,
    name: "Logitech Trackman Marble",
    supplier: "Logitech",
    description: "Ergonomic wired trackball mouse.",
    category: "Mouse",
    cost: 29.99,
  },

  // ⌨️ Regular Keyboards
  {
    id: 26,
    supplier_id: 1,
    name: "Logitech MX Keys",
    supplier: "Logitech",
    description: "Wireless illuminated keyboard for productivity.",
    category: "Keyboard",
    cost: 119.99,
  },
  {
    id: 27,
    supplier_id: 1,
    name: "Logitech K380",
    supplier: "Logitech",
    description: "Compact multi-device Bluetooth keyboard.",
    category: "Keyboard",
    cost: 39.99,
  },
  {
    id: 28,
    supplier_id: 1,
    name: "Logitech Ergo K860",
    supplier: "Logitech",
    description: "Split ergonomic wireless keyboard.",
    category: "Keyboard",
    cost: 129.99,
  },
  {
    id: 29,
    supplier_id: 1,
    name: "Logitech K120",
    supplier: "Logitech",
    description: "Affordable wired keyboard for everyday use.",
    category: "Keyboard",
    cost: 19.99,
  },
  {
    id: 30,
    supplier_id: 1,
    name: "Logitech Craft",
    supplier: "Logitech",
    description: "Wireless keyboard with creative input dial.",
    category: "Keyboard",
    cost: 199.99,
  },

  // 📹 Webcams
  {
    id: 31,
    supplier_id: 1,
    name: "Logitech C920 HD Pro",
    supplier: "Logitech",
    description: "1080p HD webcam with stereo audio.",
    category: "Webcam",
    cost: 79.99,
  },
  {
    id: 32,
    supplier_id: 1,
    name: "Logitech C922 Pro Stream",
    supplier: "Logitech",
    description: "1080p streaming webcam with background replacement.",
    category: "Webcam",
    cost: 99.99,
  },
  {
    id: 33,
    supplier_id: 1,
    name: "Logitech Brio 4K",
    supplier: "Logitech",
    description: "Ultra HD 4K webcam with HDR.",
    category: "Webcam",
    cost: 199.99,
  },
  {
    id: 34,
    supplier_id: 1,
    name: "Logitech StreamCam",
    supplier: "Logitech",
    description: "1080p60 webcam optimized for creators.",
    category: "Webcam",
    cost: 169.99,
  },
  {
    id: 35,
    supplier_id: 1,
    name: "Logitech C270",
    supplier: "Logitech",
    description: "Affordable 720p webcam for everyday use.",
    category: "Webcam",
    cost: 29.99,
  },

  // 🎤 Microphones
  {
    id: 36,
    supplier_id: 1,
    name: "Blue Yeti",
    supplier: "Logitech",
    description: "USB condenser microphone with multiple patterns.",
    category: "Microphone",
    cost: 129.99,
  },
  {
    id: 37,
    supplier_id: 1,
    name: "Blue Yeti Nano",
    supplier: "Logitech",
    description: "Compact USB microphone with cardioid and omni modes.",
    category: "Microphone",
    cost: 99.99,
  },
  {
    id: 38,
    supplier_id: 1,
    name: "Blue Snowball iCE",
    supplier: "Logitech",
    description: "Affordable plug-and-play USB microphone.",
    category: "Microphone",
    cost: 49.99,
  },
  {
    id: 39,
    supplier_id: 1,
    name: "Blue Yeti X",
    supplier: "Logitech",
    description: "Premium USB microphone with LED metering.",
    category: "Microphone",
    cost: 169.99,
  },
  {
    id: 40,
    supplier_id: 1,
    name: "Blue Snowball",
    supplier: "Logitech",
    description: "Classic USB condenser mic for creators.",
    category: "Microphone",
    cost: 69.99,
  },
  ...competitorProducts,
];
