import { Product } from "./types";

export const products: Product[] = [
  // 🎮 Gaming Mice
  {
    id: 1,
    name: "Logitech G502 HERO",
    supplier: "Logitech",
    description: "High-performance wired gaming mouse with 25K sensor.",
    category: "Gaming Mouse",
    cost: 79.99,
  },
  {
    id: 2,
    name: "Logitech G Pro X Superlight",
    supplier: "Logitech",
    description: "Lightweight wireless gaming mouse designed for esports.",
    category: "Gaming Mouse",
    cost: 149.99,
  },
  {
    id: 3,
    name: "Logitech G203 Lightsync",
    supplier: "Logitech",
    description: "Budget-friendly RGB gaming mouse with 8K DPI.",
    category: "Gaming Mouse",
    cost: 39.99,
  },
  {
    id: 4,
    name: "Logitech G305 Lightspeed",
    supplier: "Logitech",
    description:
      "Wireless gaming mouse with HERO sensor and 250h battery life.",
    category: "Gaming Mouse",
    cost: 59.99,
  },
  {
    id: 5,
    name: "Logitech G402 Hyperion Fury",
    supplier: "Logitech",
    description: "FPS-optimized wired gaming mouse with hybrid sensor.",
    category: "Gaming Mouse",
    cost: 49.99,
  },

  // 🎮 Gaming Keyboards
  {
    id: 6,
    name: "Logitech G915 TKL",
    supplier: "Logitech",
    description:
      "Wireless RGB mechanical gaming keyboard with low profile switches.",
    category: "Gaming Keyboard",
    cost: 229.99,
  },
  {
    id: 7,
    name: "Logitech G Pro X",
    supplier: "Logitech",
    description:
      "Esports-grade mechanical keyboard with hot-swappable switches.",
    category: "Gaming Keyboard",
    cost: 149.99,
  },
  {
    id: 8,
    name: "Logitech G413",
    supplier: "Logitech",
    description: "Backlit mechanical gaming keyboard with Romer-G switches.",
    category: "Gaming Keyboard",
    cost: 89.99,
  },
  {
    id: 9,
    name: "Logitech G213 Prodigy",
    supplier: "Logitech",
    description: "Spill-resistant gaming keyboard with RGB lighting.",
    category: "Gaming Keyboard",
    cost: 69.99,
  },
  {
    id: 10,
    name: "Logitech G910 Orion Spectrum",
    supplier: "Logitech",
    description: "Full-size RGB mechanical keyboard with ARX control dock.",
    category: "Gaming Keyboard",
    cost: 179.99,
  },

  // 🎧 Gaming Headset (Wired)
  {
    id: 11,
    name: "Logitech G432",
    supplier: "Logitech",
    description: "Wired gaming headset with 7.1 surround sound.",
    category: "Gaming Headset (Wired)",
    cost: 79.99,
  },
  {
    id: 12,
    name: "Logitech G Pro X",
    supplier: "Logitech",
    description: "Wired esports headset with Blue VO!CE microphone tech.",
    category: "Gaming Headset (Wired)",
    cost: 129.99,
  },
  {
    id: 13,
    name: "Logitech G633 Artemis Spectrum",
    supplier: "Logitech",
    description: "RGB wired gaming headset with DTS surround sound.",
    category: "Gaming Headset (Wired)",
    cost: 99.99,
  },
  {
    id: 14,
    name: "Logitech G230",
    supplier: "Logitech",
    description: "Lightweight wired stereo gaming headset.",
    category: "Gaming Headset (Wired)",
    cost: 49.99,
  },
  {
    id: 15,
    name: "Logitech G35",
    supplier: "Logitech",
    description: "Wired surround sound gaming headset with on-ear controls.",
    category: "Gaming Headset (Wired)",
    cost: 89.99,
  },

  // 🎧 Gaming Headset (Wireless)
  {
    id: 16,
    name: "Logitech G733 Lightspeed",
    supplier: "Logitech",
    description:
      "Wireless gaming headset with RGB lighting and Blue VO!CE mic.",
    category: "Gaming Headset (Wireless)",
    cost: 149.99,
  },
  {
    id: 17,
    name: "Logitech G935",
    supplier: "Logitech",
    description: "Wireless 7.1 surround gaming headset with 12-hour battery.",
    category: "Gaming Headset (Wireless)",
    cost: 169.99,
  },
  {
    id: 18,
    name: "Logitech G533",
    supplier: "Logitech",
    description: "DTS Headphone:X surround wireless gaming headset.",
    category: "Gaming Headset (Wireless)",
    cost: 129.99,
  },
  {
    id: 19,
    name: "Logitech G930",
    supplier: "Logitech",
    description: "Wireless gaming headset with Dolby 7.1 surround sound.",
    category: "Gaming Headset (Wireless)",
    cost: 139.99,
  },
  {
    id: 20,
    name: "Logitech Astro A50 (Logitech-owned brand)",
    supplier: "Logitech",
    description: "Premium wireless gaming headset with charging dock.",
    category: "Gaming Headset (Wireless)",
    cost: 299.99,
  },

  // 🖱️ Regular Mice
  {
    id: 21,
    name: "Logitech MX Master 3S",
    supplier: "Logitech",
    description: "Advanced wireless mouse with MagSpeed scroll wheel.",
    category: "Mouse",
    cost: 99.99,
  },
  {
    id: 22,
    name: "Logitech MX Anywhere 3",
    supplier: "Logitech",
    description: "Portable wireless mouse for mobile work.",
    category: "Mouse",
    cost: 79.99,
  },
  {
    id: 23,
    name: "Logitech M510",
    supplier: "Logitech",
    description: "Wireless mouse with back/forward buttons.",
    category: "Mouse",
    cost: 39.99,
  },
  {
    id: 24,
    name: "Logitech M185",
    supplier: "Logitech",
    description: "Simple, budget-friendly wireless mouse.",
    category: "Mouse",
    cost: 19.99,
  },
  {
    id: 25,
    name: "Logitech Trackman Marble",
    supplier: "Logitech",
    description: "Ergonomic wired trackball mouse.",
    category: "Mouse",
    cost: 29.99,
  },

  // ⌨️ Regular Keyboards
  {
    id: 26,
    name: "Logitech MX Keys",
    supplier: "Logitech",
    description: "Wireless illuminated keyboard for productivity.",
    category: "Keyboard",
    cost: 119.99,
  },
  {
    id: 27,
    name: "Logitech K380",
    supplier: "Logitech",
    description: "Compact multi-device Bluetooth keyboard.",
    category: "Keyboard",
    cost: 39.99,
  },
  {
    id: 28,
    name: "Logitech Ergo K860",
    supplier: "Logitech",
    description: "Split ergonomic wireless keyboard.",
    category: "Keyboard",
    cost: 129.99,
  },
  {
    id: 29,
    name: "Logitech K120",
    supplier: "Logitech",
    description: "Affordable wired keyboard for everyday use.",
    category: "Keyboard",
    cost: 19.99,
  },
  {
    id: 30,
    name: "Logitech Craft",
    supplier: "Logitech",
    description: "Wireless keyboard with creative input dial.",
    category: "Keyboard",
    cost: 199.99,
  },

  // 📹 Webcams
  {
    id: 31,
    name: "Logitech C920 HD Pro",
    supplier: "Logitech",
    description: "1080p HD webcam with stereo audio.",
    category: "Webcam",
    cost: 79.99,
  },
  {
    id: 32,
    name: "Logitech C922 Pro Stream",
    supplier: "Logitech",
    description: "1080p streaming webcam with background replacement.",
    category: "Webcam",
    cost: 99.99,
  },
  {
    id: 33,
    name: "Logitech Brio 4K",
    supplier: "Logitech",
    description: "Ultra HD 4K webcam with HDR.",
    category: "Webcam",
    cost: 199.99,
  },
  {
    id: 34,
    name: "Logitech StreamCam",
    supplier: "Logitech",
    description: "1080p60 webcam optimized for creators.",
    category: "Webcam",
    cost: 169.99,
  },
  {
    id: 35,
    name: "Logitech C270",
    supplier: "Logitech",
    description: "Affordable 720p webcam for everyday use.",
    category: "Webcam",
    cost: 29.99,
  },

  // 🎤 Microphones
  {
    id: 36,
    name: "Blue Yeti",
    supplier: "Logitech",
    description: "USB condenser microphone with multiple patterns.",
    category: "Microphone",
    cost: 129.99,
  },
  {
    id: 37,
    name: "Blue Yeti Nano",
    supplier: "Logitech",
    description: "Compact USB microphone with cardioid and omni modes.",
    category: "Microphone",
    cost: 99.99,
  },
  {
    id: 38,
    name: "Blue Snowball iCE",
    supplier: "Logitech",
    description: "Affordable plug-and-play USB microphone.",
    category: "Microphone",
    cost: 49.99,
  },
  {
    id: 39,
    name: "Blue Yeti X",
    supplier: "Logitech",
    description: "Premium USB microphone with LED metering.",
    category: "Microphone",
    cost: 169.99,
  },
  {
    id: 40,
    name: "Blue Snowball",
    supplier: "Logitech",
    description: "Classic USB condenser mic for creators.",
    category: "Microphone",
    cost: 69.99,
  },
];
